### ISSUE TITLE
History展示的相关问题

### ISSUE THREAD

**Issue by tbeeqgnui** [artistic709/simpleswap#11]
1. ![image](https://user-images.githubusercontent.com/6813777/67846561-63a6dc00-fb3c-11e9-96f2-97f1f245a29f.png)
不应该将不同账户地址的history展示在了一起，如图：两个unlock动作来自不同的地址。

2. 历史记录倒序展示，最新的在最上面
![image](https://user-images.githubusercontent.com/6813777/67846856-da43d980-fb3c-11e9-9f4b-fe8025653ce6.png)

**Comment by Xiawpohr** [comment]
已解決。
