### ISSUE TITLE
swap时输入框上的 (估计) 不应该交换

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#12]
![微信截图_20191030174143](https://user-images.githubusercontent.com/32669799/67846728-ac5e9500-fb3c-11e9-8b1e-f3064583ff3a.png)
![微信截图_20191030174212](https://user-images.githubusercontent.com/32669799/67846731-acf72b80-fb3c-11e9-9a1d-65e6390ca058.png)

**Comment by Xiawpohr** [comment]
會顯示 "估計" 這個詞的原因是這個數量是計算出來的，而不是使用者輸入的。例如：
1. 當你想要用 T1 來獲得 6 個 USDx 時，你會在輸出的地方設定 6 USDx，然後會自動計算出大概需要數入的數量，所以這時會在輸入的標題上標示這個是一個估計值。
2. 反之當你想要用 6 USDx 來獲得 T1 時，輸出的地方就會是一個估計值。
