### ISSUE TITLE
正确添加一个token pair的相关问题

### ISSUE THREAD

**Issue by tbeeqgnui** [artistic709/simpleswap#14]
1. 目前现在default的几个pair是如何获取的？web端hard code的么？
2. 通过add liquility添加一个token pair之后，其他用户（或者仅仅是换一个浏览器）可以不通过search就发现这个pair麽？目前的状况是，每次重新载入页面或换一个浏览器，在swap/pool的token list中无法发现新加入的pair，需要先search。

**Comment by Xiawpohr** [comment]
1. 目前的 default token pairs 是 hardcode 在程式碼中的，原因是不應該很方便讓使用者在網頁上交易來路不明的 tokens，所以 uniswap 已經整理好預設顯示的白名單 (mainnet)，當使用者要交易白名單以外的 token 時，再用搜尋功能。

2. 目前這樣的行為是正確的。如果想要增加 default token pairs，要在白名單上增加。

**Comment by Donald-Nobel** [comment]
白名单在哪里？服务器还是合约里面？

**Comment by Xiawpohr** [comment]
白名單是寫在前端的程式碼中。

**Comment by zxyge** [comment]
如果白名单放在代码中新加default token pairs都需要修改代码，不凡便后期维护。可否在host了放个json文件存储白名单

**Comment by Xiawpohr** [comment]
可以。

**Comment by Xiawpohr** [comment]
已完成溝通。
