### ISSUE TITLE
输入框中上划鼠标滚轮出现科学计数

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#16]
![微信截图_20191031105139](https://user-images.githubusercontent.com/32669799/67915089-f8f1b100-fbcc-11e9-99ed-ac6aa5512279.png)

**Comment by zxyge** [comment]
所有输入框都有这个问题

**Comment by zxyge** [comment]
firefox上没有此问题

**Comment by Xiawpohr** [comment]
已解決。
