### ISSUE TITLE
页面样式与设计稿不同

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#17]
设计稿：
![微信截图_20191031115215](https://user-images.githubusercontent.com/32669799/67917743-f1360a80-fbd4-11e9-8268-d372ea1769ad.png)

页面：
![Screenshot from 2019-10-31 11-46-16](https://user-images.githubusercontent.com/32669799/67917680-b8963100-fbd4-11e9-94ce-50be2938f2ca.png)

**Comment by Xiawpohr** [comment]
已解決。
