### ISSUE TITLE
token 的icon是如何获取和存储的

### ISSUE THREAD

**Issue by Donald-Nobel** [artistic709/simpleswap#18]

**Comment by Xiawpohr** [comment]
目前 token 的 icon 是 host 在我的 github repo 上。

**Comment by Donald-Nobel** [comment]
可以这样解决：
1. default的token，icon存在服务器，然后下载到浏览器本地，缓存；
2. 没有default的token，有一个默认的icon，所有非default的token都用这个，直到被加入default list；

**Comment by Xiawpohr** [comment]
已解決。
