### ISSUE TITLE
按照设计稿修改页面样式

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#19]
![页面修改](https://user-images.githubusercontent.com/32669799/67924205-f30ac880-fbea-11e9-8e19-3a1372fed766.png)

**Comment by zxyge** [comment]
![添加流动资金](https://user-images.githubusercontent.com/32669799/67928312-a8db1480-fbf5-11e9-9f27-5f9c542e5bb8.png)

**Comment by zxyge** [comment]
此页面差别较大，仅标识出明显的两处。请参照UI设计稿修改https://lanhuapp.com/web/#/item/project/board/detail?pid=06304e49-854d-47a6-a0ea-d9984cebe894&project_id=06304e49-854d-47a6-a0ea-d9984cebe894&image_id=33ace627-2a41-4e87-b21f-095e1e08702f

**Comment by Xiawpohr** [comment]
已解決。
