### ISSUE TITLE
链接rinkeby网络时没有提示信息

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#21]
https://lanhuapp.com/web/#/item/project/board/detail?pid=06304e49-854d-47a6-a0ea-d9984cebe894&project_id=06304e49-854d-47a6-a0ea-d9984cebe894&image_id=ec5656c9-e5a0-4ff5-a414-14cfe0f11b4f
请参考设计图完成页面

**Comment by Xiawpohr** [comment]
已解決。
