### ISSUE TITLE
增加footer后页面出现滚动条

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#22]
![微信截图_20191106164553](https://user-images.githubusercontent.com/32669799/68285673-ac214500-00ba-11ea-88c6-1949a1e9795a.png)

![微信截图_20191106173824](https://user-images.githubusercontent.com/32669799/68286576-4766ea00-00bc-11ea-905b-81653805ea02.png)
可否重写此段css，修改100vh高度

**Comment by tbeeqgnui** [comment]
为什么会出现两个滚动条？
![image](https://user-images.githubusercontent.com/6813777/68287226-57cb9480-00bd-11ea-9e26-876c16408d9a.png)

**Comment by Xiawpohr** [comment]
我無法重現這個問題。請問你們使用的瀏覽器與作業系統是什麼呢？

**Comment by Donald-Nobel** [comment]
chrome for mac.

**Comment by Donald-Nobel** [comment]
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/48235929/68455427-55d91100-0236-11ea-8d00-21bf04353600.png">

**Comment by Xiawpohr** [comment]
測試了 mac 上 chrome、firefox、safari，都無法復現。
