### ISSUE TITLE
页面语言没有随浏览器语言改变

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#23]
浏览器设置为英文后页面仍显示中文。请参考lendf.me做到页面语言随浏览器语言切换
![lendf中文](https://user-images.githubusercontent.com/32669799/68287290-7598f980-00bd-11ea-90e4-41fa3d8cf1ea.png)
![lendf英文](https://user-images.githubusercontent.com/32669799/68287291-7598f980-00bd-11ea-8c5e-bf9c809d75e6.png)
![simpleswap中文](https://user-images.githubusercontent.com/32669799/68287300-7893ea00-00bd-11ea-93bf-467c2ed8a709.png)
![simple](https://user-images.githubusercontent.com/32669799/68287304-7893ea00-00bd-11ea-9d7a-f5efb5ce3479.png)

**Comment by Xiawpohr** [comment]
已解決。
