### ISSUE TITLE
添加白名单已存在token时提示token不存在

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#26]
![微信截图_20191106181847](https://user-images.githubusercontent.com/32669799/68289875-e80bd880-00c1-11ea-8bcd-df36d595c61a.png)
![微信截图_20191106181911](https://user-images.githubusercontent.com/32669799/68289892-f35f0400-00c1-11ea-9ca7-a71f5cb2ee19.png)

**Comment by Xiawpohr** [comment]
因為你在 Rinkeby 上，Rinkeby 上只有 USDs, COW, T1, T2。
白名單上的 tokens 是在主網上的。
