### ISSUE TITLE
swap页面增加默认token对

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#27]
默认token1为USDx，默认token2可在白名单中给个属性控制。通过下拉菜单可以选择

**Comment by tbeeqgnui** [comment]
这个地方的设计是这样的：在swap页面，会有一个默认的交易对，没有Select a token这个界面，如果用户需要选择token，点击已经显示的token去select即可。例如默认的pair可以是 USDx/TokenA，TokenA可能是USDT，我们有办法依照某个规则来设定谁是TokenA即可。

**Comment by Xiawpohr** [comment]
我目前會將 TokenA 設定為白名單的第一個。

**Comment by Xiawpohr** [comment]
已解決。
