### ISSUE TITLE
addLiquidity时点击输入框上的balance不能输入最大值

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#29]
![微信截图_20191106183712](https://user-images.githubusercontent.com/32669799/68291276-77b28680-00c4-11ea-866a-4f5b88139a45.png)

**Comment by Xiawpohr** [comment]
已解決。

**Comment by zxyge** [comment]
![微信截图_20191108173950](https://user-images.githubusercontent.com/32669799/68466176-d6a40700-024e-11ea-8699-1188e816c889.png)
点击max时上下两个输入框都填入了数字

**Comment by Xiawpohr** [comment]
當你點擊 max 時，會幫你自動輸入 USDx 的最大值。
填入 USDx 後，會自動幫你估算出同時所需要存入的 TEST 代幣。
這裡 USDx-TEST pairs 剛好是 1:1，所以你會看到兩個輸入框都輸入差不多的數字。
這個不是 bug。
