### ISSUE TITLE
数字相关的问题

### ISSUE THREAD

**Issue by Donald-Nobel** [artistic709/simpleswap#32]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/48235929/68448211-b6a81f80-021d-11ea-95f1-ae8a765187e6.png">

1. 点击max无效；
2. 数字应采用千分位展示，默认有两位小数；

**Comment by Xiawpohr** [comment]
1. `Enter Max` 是滑鼠以滑鼠 hover 到 balance 上的提示文字，不是按鈕。
2. 已解決，數字採用千分位展示。
