### ISSUE TITLE
未连接主网时的提示是错误的

### ISSUE THREAD

**Issue by Donald-Nobel** [artistic709/simpleswap#33]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/48235929/68453060-718ce900-022f-11ea-996d-e3b5d35423e7.png">
此时的提示应为：“请连接钱包”

**Comment by Xiawpohr** [comment]
這個畫面在正式上線到主網上，就不會出現了。

你會看到這個畫面的原因是，當使用者還沒有登入的時候，也就是還沒連結到 MetaMask 錢包時，前端這邊會連接到 infura 上，目的是讓使用者還沒登入時，也可以使用 dapp 進行一些試算行為。

現在是還在測試階段，所以是連接 rinkeby infura。當正式將網站上線到主網時，就會改成 mainnet infura，這個提示也就不會再出現了。
