### ISSUE TITLE
swap页面输入好数值后点击交换输入输出的箭头，输入框变红

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#6]
操作如图

![微信截图_20191024170055](https://user-images.githubusercontent.com/32669799/67470179-ec76d100-f67f-11e9-95fe-b7b5ce79a167.png)
![微信截图_20191024165932](https://user-images.githubusercontent.com/32669799/67470180-ed0f6780-f67f-11e9-9e65-9f25c033a313.png)
![微信截图_20191024170027](https://user-images.githubusercontent.com/32669799/67470181-ed0f6780-f67f-11e9-9e1f-02aabab6e3cb.png)

**Comment by Xiawpohr** [comment]
無法重現這個問題。請問可以提供重現這個 Bugs 的操作流程嗎？

**Comment by zxyge** [comment]
[复现步骤.zip](https://github.com/artistic709/simpleswap/files/3792069/default.zip)

**Comment by Xiawpohr** [comment]
上面那個是一個壞掉的影片。
我剛剛仔細看了圖片，會出現紅色警告，應該是因為資金池中沒有足夠多代幣給你兌換。

**Comment by Xiawpohr** [comment]
無法復現，且沒有再出現這個問題。
