### ISSUE TITLE
swap完成后页面“输出”输入框数值更新慢，可以按原来数值唤起钱包，但合约执行失败

### ISSUE THREAD

**Issue by zxyge** [artistic709/simpleswap#7]
swap完成后页面“输出”输入框数值更新慢，可以按原来数值唤起钱包，但合约执行失败

**Comment by Xiawpohr** [comment]
無法重現這個問題。請問可以提供重現這個 Bugs 的操作流程嗎？

**Comment by zxyge** [comment]
解决完https://github.com/artistic709/simpleswap/issues/3 后，此issues没有再复现
